# Makefile for dotfiles-spaces
#
    #  Using ~/.dotmake:
    #  ----------------
    #    Both Devx Spaces and github Codespaces will symlink our ~/.dotmake launcher into
    #    the HOME tree.  (The launcher invokes our Makefile after first capturing the cwd to ORGDIR,
    #    and then changing to the ~/dotfiles-spaces dir.)
    #
    #

SHELL=/bin/bash
.ONESHELL:
.SUFFIXES:
MAKEFLAGS += --no-builtin-rules --no-print-directory
.SHELLFLAGS= -uec
absdir := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
Makefile = $(absdir)Makefile
.DEFAULT_GOAL := Config
Makefile: ;



# Create+include .env.mk and .metatargets.mk:
include $(absdir).env.mk          # Autogenerated on every run
include $(absdir).metatargets.mk  # Autogenerated on every run

VscodeUserDir = $(HOME)/.local/share/code-server/User
VscodeSettingsOrg = bbgithub:$(User)
GhPubOrg = https://github.com/Stabledog

Flag := $(HOME)/.flag-dotfiles

# Individual feature targets have their own makefiles:
include $(shell ls inc/*.mk)


# Top-level config:
#  (Other config targets should cite this as a dependency to get nice output ordering)
Config: .cfg.top
.PHONY: Config
.cfg.top: $(Finit)
	@set -ue

	cat <<-EOF
	#  $(absdir)Makefile:
	Makefile=$(Makefile)
	Code=$(Code)
	absdir=$(absdir)
	User=$(User)
	DOTFILES_SYS=$(DOTFILES_SYS)
	GITHUB_USER=$(GITHUB_USER)
	ISBB=$(ISBB)
	Flag=$(Flag)
	Flags="$(shell ls $(Flag))"
	VscodeSettingsOrg=$(VscodeSettingsOrg)
	VscodeUserDir=$(VscodeUserDir)
	GhPubOrg=$(GhPubOrg)
	Megadeps="$(Megadeps)"
	ORGDIR="$(ORGDIR)"

	EOF
.cfg-export:
	@# Add export decl to all config values:
	$(MAKE) -f $(Makefile) Config | awk '/^[^#]+/ {print "export " $$0}'


$(absdir).env.mk: $(absdir)bin/env-detect $(absdir)Makefile
	@set -ue # Environment detection comes before any conditional stuff
	$< > $@

$(absdir).metatargets.mk: $(absdir)Makefile $(absdir).env.mk
	@set -ue # metatargets like 'mega' need some conditional logic
	source $(absdir).env.mk
	{
		echo "DOTFILES_SYS=$${DOTFILES_SYS}"
		case "$${DOTFILES_SYS}" in
		 	codespaces) echo 'Megadeps=mega-codespaces' ;;
		 	devxspaces) echo 'Megadeps=mega-devxspaces' ;;
		 	wsl) echo 'Megadeps=mega-wsl' ;;
			*) exit 19  # Bad DOTFILES_SYS value
		 esac
	} > $@

# Targets which touch a flag in $(Flag) should depend on $(Finit)
Finit=$(Flag)/.init
$(Flag)/.init:
	mkdir -p $(Flag)
	echo "$(Flag) 1" >> $(HOME)/.tox-index
	echo "$(HOME)/dotfiles" >> $(HOME)/.tox-index
	touch $@


mega-devxspaces: \
	makestuff \
	vbase \
	spaceup \
	vscodevim \
	vsweb-settings \
	app-setup \
	vimsane
	@set -ue
	echo "Ok: $@"

mega-codespaces: \
	makestuff \
	vbase
	echo "Ok: $@"

mega-wsl: \
	vimsane
	echo "Ok: $@"


mega: $(Megadeps)


clean: .top-clean
.top-clean:
	@ # Remove stuff to try again:
	rm $(absdir).env.mk $(absdir).metatargets.mk || :
	[[ -d $(Flag) ]] && rm $(Flag)/* &>/dev/null || :
	true

